version: "3"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ENVIRONEMT=development
      - SECRET_KEY=p_o3vp1rg5)t^lxm9-43%0)s-=1qpeq%o7gfq+e4#*!t+_ev82
      - DEBUG=True
      - STRIPE_TEST_PUBLISHABLE_KEY=<pk_test_your_publishable_key_here>
      - STRIPE_TEST_SECRET_KEY=<sk_test_your_secret_key_here>
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - NAME=postgres
      - USER=postgres
      - PASSWORD=postgres

volumes:
  postgres_data: